sudo: required
services:
  - docker

before_install:
  - docker build -t tricaole/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tricaole/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  evn: "DockerReact-env-2"
  bucket_name: "elasticbeanstalk-ap-southeast-1-443865620508"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY